definitions:
  handler.CreateLeadRequest:
    properties:
      age:
        type: integer
      client:
        type: boolean
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  handler.CreateLeadResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.LeadRespose'
      message:
        type: string
    type: object
  handler.DeleteLeadResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.LeadRespose'
      message:
        type: string
    type: object
  handler.ShowLeadResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.LeadRespose'
      message:
        type: string
    type: object
  handler.UpdateLeadRequest:
    properties:
      age:
        type: integer
      client:
        type: boolean
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  handler.UpdateLeadResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.LeadRespose'
      message:
        type: string
    type: object
  schemas.LeadRespose:
    properties:
      client:
        type: boolean
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      salary:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /lead:
    delete:
      consumes:
      - application/json
      description: Delete a lead in database
      parameters:
      - description: Lead id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteLeadResponse'
      summary: Delete lead
      tags:
      - Leads
    get:
      consumes:
      - application/json
      description: Show a specifc lead in database
      parameters:
      - description: Lead id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowLeadResponse'
      summary: Show lead
      tags:
      - Leads
    post:
      consumes:
      - application/json
      description: Create a new lead in database
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateLeadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateLeadResponse'
      summary: Create lead
      tags:
      - Leads
  /leads:
    get:
      consumes:
      - application/json
      description: Show all leads in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowLeadResponse'
      summary: Show leads
      tags:
      - Leads
    put:
      consumes:
      - application/json
      description: Update a leads in database
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateLeadRequest'
      - description: Lead id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateLeadResponse'
      summary: Update lead
      tags:
      - Leads
swagger: "2.0"
